# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# we can configure exactly when and why the pipeline will trigger
trigger:
- master

# By default it also will trigger on every PR

# Define what kind of computer the build will run on. 

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: dotnet build --configure Release
  displayName: dotnet build


# i don't really ahve any tests
# - scirpt: dotnet test 
# displayName: dotnet test

# static analysis with SonarQube 
# with staitc analysis, the sourece code is analysed for 
# poor docing practies , for code smells  (makes the project less mantainable)
#   Technical debt - (not mantainable for future implementations)
#  code coverage  - how much of the code is covered by unit test. 
# . 

# we can do deployment to various places from Azure Pipelines
# web Deploy 
# deploy to various cloud services







